### ISSUE TITLE
Windows Git Bash command: npm run serve - failing

### ISSUE THREAD

**Issue by reutmenashe** [tldrrun/tools.tldr.run#10]
15 verbose Windows_NT 10.0.18362
16 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve"
17 verbose node v12.16.3
18 verbose npm  v6.14.4
19 error code ELIFECYCLE
20 error errno 255
21 error tools.tldr.run@0.1.0 preserve: `cat tools/*.json | jq -s 'flatten' > public/assets/main.json`
21 error Exit status 255
22 error Failed at the tools.tldr.run@0.1.0 preserve script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 255, true ]

**Comment by madhuakula** [comment]
Looks like you don't have `jq` utility installed. Install `jq` from https://stedolan.github.io/jq/

Also I haven't tested the setup in Windows, please let me know if your feedback.

Thanks

**Comment by reutmenashe** [comment]
ye seem to be very problematic, going to move to Ubunto.

**Comment by madhuakula** [comment]
Hey @reutmenashe 

Looks like one of JSON files in `tools` directory has `,` and I fixed them, also created Docker container as well. Soon I will add JSON linting as well. So I am closing this issue for now. Please re-open if anything missing.

Thanks again!
