### ISSUE TITLE
CSS bug for card title/header

### ISSUE THREAD

**Issue by madhuakula** [tldrrun/tools.tldr.run#18]
Looks like the recent update has broken the tool card header/title visible much larger in size.

<img width="1792" alt="Screenshot 2020-05-31 at 10 58 54" src="https://user-images.githubusercontent.com/6764192/83348541-eb9cd080-a32d-11ea-9f57-e207a60ffa12.png">

@apvarun could you please have a look at it?

Thanks 😃

**Comment by apvarun** [comment]
Submitted a PR #19
