### ISSUE TITLE
Maintenance status indication

### ISSUE THREAD

**Issue by stiliyana-simeonova** [tldrrun/tools.tldr.run#9]
it would be good to have a an indication on how well maintained the project is - for example "active development", "EoL announced", "out of support", "discontinued" etc.

**Comment by madhuakula** [comment]
Hello @stiliyana-simeonova 

Thanks for adding the suggestion. We really appreciate giving more feedback and suggestion. Apart from this we also have bunch of thing in our upcoming features like docker image, documentation, etc. Also stats from Github URL like stars, forks, last commit will give the current status of the project (I think we can use the data from this to understand provide near real-time status of the current project status)

I will keep this feedback in mind when we release those feature.

Thanks once again for the help and I really appreciate the suggestion and would love to hear more feedback to improve :)

**Comment by stiliyana-simeonova** [comment]
I agree, will have a look at the code base and see if I could contribute :)

Thanks

**Comment by madhuakula** [comment]
That would be awesome. Also, here not much backend code is there specifically yet. Still local bash, python scripts 😛 

But let me know if you need more information about anything to contribute. Happy to provide :)

**Comment by madhuakula** [comment]
Closing this issue for now. As we are handling in future development updates.

Thank you so much once again for suggestion!
